version: "3"
services:
  mqtt:
    restart: unless-stopped
    image: "eclipse-mosquitto"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
  camera:
    restart: unless-stopped
    image: "ghcr.io/devantler/software-engineering-f22/camera-color-scanner:latest"