version: "3"
services:
  mqtt:
    restart: unless-stopped
    image: "eclipse-mosquitto"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
  camera:
    restart: unless-stopped
    image: "ghcr.io/devantler/software-engineering-f22/camera-color-scanner:latest"
      #    devices:
      #- "/dev/video0:/dev/video0"
      #- "/dev/video1:/dev/video1"
    volumes:
      - "./image.bmp:/app/image.bmp:ro"
