name: Orchestrator-Service-Docker

on:
  push:
    branches: ['main']
    # paths:
    #   - 'SemesterProject/RaspberryPi/OrchestratorService/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: SemesterProject/RaspberryPi/OrchestratorService
          file: SemesterProject/RaspberryPi/OrchestratorService/Dockerfile
          platform: linux/arm/v7
          push: true
          tags: devantler/software-engineering-f22/orchestrator-service:latest
          
