name: Raspi-Camera-Docker

on:
  push:
    branches: ['main']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          tag=ghcr.io/devantler/software-engineering-f22/camera-color-scanner
          docker buildx create --use
          docker buildx build --push -t $tag:latest -t $tag:${{github.sha}} --platform linux/arm/v7,linux/arm64,linux/amd64 ./SemesterProject/RaspberryPi/CameraColorScanner
          
          
